#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "👉 Running pre-commit hook..."

# Run lint and prettier fixes
npm run format

# If any files are fixed (i.e., linting or prettier), stage them for commit
git add .

# If everything is good, continue with the commit
if [ $? -eq 0 ]; then
  echo "✅ Format & lint passed. Ready to commit! 🚀"
else
  echo "❌ Format or lint failed. Commit aborted. 💥"
  exit 1
fi
